#!/bin/bash
cd /Users/ricardosantoyo/Documents/projects/uxdsl
SYMS="updatePalette updateColor applyColors getColor resetColors loadPersistedColors applyPalette getPalette resetPalette loadPersisted( updateSpacing applySpacing getSpacing resetSpacing loadPersistedSpacing link( unlink( getBreakpoints applyBreakpoints updateBreakpoint resetBreakpoints loadPersistedBreakpoints subscribe( applyTheme getAppliedTheme resetTheme loadPersistedTheme subscribeTheme DEFAULT_THEME_STYLE_ID DEFAULT_THEME_STORAGE_KEY LEGACY_STORAGE_KEYS themeStructure structuralChanges generateThemeCss validateAndNormalizeTheme deepMergeTheme cloneThemeValue KNOWN_THEME_FAMILIES THEME_SCHEMA_KEY checkThemeContrast parseLiteralColor relativeLuminance contrastRatio compositeOver resolveExpression generateTypographyCss compileTypographyRules resolveTypographyRole typographyValueToCss TYPOGRAPHY_PROPERTIES TYPOGRAPHY_CSS_PROPERTIES inspectTypographyTheme generateEdgeCss inspectEdgeTheme getEdgeTokens compileEdgeRules edgeValueToCss DEFAULT_BORDERS DEFAULT_RADII DEFAULT_BORDER_COLORS RADIUS_KEYWORDS generateShadowCss inspectShadowTheme getShadowTokens compileShadowRules DEFAULT_SHADOWS generateSurfaceCss inspectSurfaceTheme surfaceDeclarations getSurfaceTokens parseSurfaceArguments parseOverrideArguments surfaceValueToCss compileSurfaceRules DEFAULT_SURFACES SURFACE_PROPERTIES generateButtonCss inspectButtonTheme buttonComponentCss buttonDeclarations getButtonTokens compileButtonRules parseButtonArguments DEFAULT_BUTTONS BUTTON_PROPERTIES BUTTON_STATES generateInputCss inspectInputTheme inputComponentCss inputDeclarations getInputTokens compileInputRules parseInputArguments DEFAULT_INPUTS INPUT_PROPERTIES INPUT_STATES generateDensityCss DEFAULT_BREAKPOINTS DEFAULT_DENSITIES getDensityTokens inspectReferences ReferenceIntegrityError DEFAULT_THEME getDefaultTheme resolveTheme encodeGoogleFontFamily googleFontsImportUrls responsiveEntries resolveResponsiveValue inspectResponsiveValue getToneFamilies compileDensityRules defineConfig discoverThemeSync discoverThemeAsync findThemeConfigPath loadThemeConfigSync loadThemeConfigAsync THEME_CANDIDATES normalizeThemeExport warnIfLooksLikeBuildConfig collectLocalRequireTree clearLocalRequireCache themeVar spaceVar colorVar includeTheme configRoot discoverTheme __resetThemeStateForTests"
for sym in $SYMS; do
  pg=$(grep -rn -F "$sym" packages/playground-nextjs/src packages/playground-nextjs/themes.js packages/playground-nextjs/next.config.js packages/playground-nextjs/postcss.config.js packages/playground-nextjs/uxdsl.config.cjs 2>/dev/null | grep -v node_modules | wc -l | tr -d ' ')
  docs=$(grep -rn -F "$sym" docs README.md AGENTS.md packages/postcss-uxdsl/README.md packages/postcss-uxdsl/docs packages/uxdsl-cli/README.md packages/uxdsl-core/README.md packages/vite-plugin-uxdsl/README.md packages/uxdsl-webpack-loader/README.md 2>/dev/null | wc -l | tr -d ' ')
  adapters=$(grep -rn -F "$sym" packages/uxdsl-cli/bin packages/uxdsl-core/src packages/vite-plugin-uxdsl/src packages/uxdsl-webpack-loader/index.js packages/uxdsl-vscode/src scripts 2>/dev/null | grep -v node_modules | wc -l | tr -d ' ')
  tests=$(grep -rln -F "$sym" packages/postcss-uxdsl/test 2>/dev/null | wc -l | tr -d ' ')
  printf "%-28s playground=%-4s docs=%-4s adapters/scripts=%-4s testfiles=%s\n" "$sym" "$pg" "$docs" "$adapters" "$tests"
done
