'use client'

import React, { useState, useMemo } from 'react'
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter'
import { vscDarkPlus } from 'react-syntax-highlighter/dist/esm/styles/prism'

export default function DemoProductivity() {
  const [count, setCount] = useState<number>(1000)
  
  // Generate dummy data
  const cards = useMemo(() => Array.from({ length: count }), [count])

  // Simulate the CSS output of the SCSS loop
  const cssOutput = `
    .stress-grid {
      display: grid;
      grid-template-columns: 1fr;
      gap: 0.5rem;
      padding: 1rem 0;
    }
    @media (min-width: 768px) {
      .stress-grid {
        grid-template-columns: repeat(auto-fill, minmax(120px, 1fr));
      }
    }
    .stress-card {
      aspect-ratio: 1;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 0.5rem;
      border-radius: 8px;
      transition: all 0.2s;
      cursor: pointer;
      text-align: center;
      position: relative;
      overflow: hidden;
    }
    .stress-card:hover {
      transform: translateY(-4px) scale(1.02);
      z-index: 1;
      box-shadow: 0 10px 20px rgba(0,0,0,0.2);
    }
    .stress-card-title {
      font-size: 1rem;
      font-weight: 700;
      margin-bottom: 0.25rem;
      line-height: 1.2;
    }
    .stress-card-badge {
      font-size: 0.7rem;
      padding: 2px 8px;
      border-radius: 12px;
      background: #ffffff;
      color: #333333;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    /* Generated by SCSS Loop */
    .stress-tone-0 { background-color: #264653; color: white; }
    .stress-tone-1 { background-color: #2a9d8f; color: white; }
    .stress-tone-2 { background-color: #e9c46a; color: #1a1a1a; }
    .stress-tone-3 { background-color: #f4a261; color: #1a1a1a; }
    .stress-tone-4 { background-color: #e76f51; color: white; }
  `

  return (
    <section id="DemoProductivity" className="demo-section">
      <style>{cssOutput}</style>
      <div className="demo-header">
        <p className="demo-subtitle">
          High-performance rendering with atomic CSS generation. 
          This demo renders <strong>{count}</strong> nodes using a simple SCSS loop to generate tone variations.
        </p>
      </div>

      <div className="productivity-controls" style={{ marginBottom: '2rem' }}>
        <label style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
          <span>Card Count: <strong>{count}</strong></span>
          <input 
            type="range" 
            min="100" 
            max="5000" 
            step="100"
            value={count} 
            onChange={e => setCount(Number(e.target.value))}
            style={{ flex: 1 }}
          />
        </label>
      </div>

      <div className="demo-layout">
        
        {/* Code Section - Stacked */}
        <div className="demo-code-stack" style={{ display: 'flex', flexDirection: 'column', gap: '2rem', marginBottom: '2rem' }}>
          <div className="demo-code-block-wrapper">
             <h4 className="demo-subtitle">SCSS / UXDSL Source</h4>
             <div className="demo-code-block">
              <SyntaxHighlighter language="scss" style={vscDarkPlus}>
{`.stress-grid {
  display: grid;
  grid-template-columns: xs(1fr) md(repeat(auto-fill, minmax(120px, 1fr)));
  gap: density(2);
}

@each $tone in $tones {
  .stress-tone-#{$tone} {
    @ds-surface(flat #{$tone} radius(3));
    aspect-ratio: 1;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    transition: all 0.2s;

    &:hover {
      transform: translateY(-4px) scale(1.02);
      box-shadow: shadow(4);
    }
    
    .title {
      @ds-typography(h6 bold);
      margin-bottom: density(1);
    }
    .badge { 
      @ds-surface(contained surface density(0) radius(full)); 
    }
  }
}`}
              </SyntaxHighlighter>
             </div>
          </div>

          <div className="demo-code-block-wrapper">
             <h4 className="demo-subtitle">TSX Implementation</h4>
             <div className="demo-code-block">
              <SyntaxHighlighter language="tsx" style={vscDarkPlus}>
{`{/* Responsive Grid Container */}
<div className="stress-grid">
  {Array.from({ length: ${count} })
    .map((_, i) => (
      <div 
        key={i} 
        className={\`stress-card 
          stress-tone-\${i % 5}\`}
      >
        <div className="stress-card-title">
          Item {i + 1}
        </div>
        <div className="stress-card-badge">
          #{i % 5}
        </div>
      </div>
    ))
  }
</div>`}
              </SyntaxHighlighter>
             </div>
          </div>
        </div>

        {/* Preview Section - Full Width */}
        <div className="demo-preview-full">
          <h4 className="demo-subtitle">Live Render ({count} nodes)</h4>
          <div className="stress-grid">
            {cards.map((_, i) => (
              <div key={i} className={`stress-card stress-tone-${i % 5}`}>
                <div className="stress-card-title">Item {i + 1}</div>
                <div className="stress-card-badge">#{i % 5}</div>
              </div>
            ))}
          </div>
        </div>

      </div>
    </section>
  )
}