// Generated by scripts/generate-language-artifacts.js. Do not edit.
export const completions = {
  "directiveArguments": {
    "ds-surface": {
      "roles": [
        "contained",
        "outlined",
        "flat"
      ],
      "tones": [
        "primary",
        "surface"
      ],
      "sizes": [
        "0",
        "1",
        "2",
        "3",
        "4",
        "5"
      ],
      "overrides": [
        "radius",
        "shadow"
      ]
    },
    "ds-button": {
      "roles": [
        "contained",
        "outlined",
        "flat"
      ],
      "tones": [
        "primary",
        "surface"
      ],
      "sizes": [
        "0",
        "1",
        "2",
        "3",
        "4",
        "5"
      ],
      "overrides": [
        "radius",
        "shadow"
      ]
    },
    "ds-input": {
      "roles": [
        "contained",
        "outlined",
        "underline"
      ],
      "tones": [
        "primary",
        "surface"
      ],
      "sizes": [
        "0",
        "1",
        "2",
        "3",
        "4",
        "5"
      ],
      "overrides": [
        "radius",
        "shadow"
      ]
    }
  },
  "directives": [
    "theme",
    "ds-surface",
    "ds-typo",
    "ds-button",
    "ds-input"
  ],
  "functions": [
    "palette",
    "color",
    "radius",
    "rounded",
    "border",
    "density",
    "shadow",
    "elevation",
    "space",
    "xs",
    "sm",
    "md",
    "lg",
    "xl"
  ]
} as const;
