// Generated by scripts/generate-language-artifacts.js. Do not edit.
export const completions = {
  "directives": [
    "theme",
    "ds-surface",
    "ds-typo",
    "ds-button"
  ],
  "functions": [
    "palette",
    "radius",
    "density",
    "shadow",
    "space",
    "xs",
    "sm",
    "md",
    "lg",
    "xl"
  ]
} as const;
